### ISSUE TITLE
UnsupportedOperationException question

### ISSUE THREAD

**Issue by nmarasoiu** [swagger-akka-http/swagger-akka-http#60] opened 2017-12-04 12:45 UTC
Hi, using the latest release, I get this exception. Please let me know how can I help with more information to track the cause of this and what I could be doing wrong. Thank you
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at io.swagger.models.Swagger.addScheme(Swagger.java:193)
	at io.swagger.jaxrs.Reader.readSwaggerConfig(Reader.java:583)
	at io.swagger.jaxrs.Reader.read(Reader.java:167)
	at com.github.swagger.akka.SwaggerGenerator.filteredSwagger(SwaggerHttpService.scala:93)
	at com.github.swagger.akka.SwaggerGenerator.filteredSwagger$(SwaggerHttpService.scala:92)
	at mcc.movie.common.swagger.SwaggerDoc.filteredSwagger(SwaggerDoc.scala:17)
	at com.github.swagger.akka.SwaggerGenerator.generateSwaggerJson(SwaggerHttpService.scala:72)
	at com.github.swagger.akka.SwaggerGenerator.generateSwaggerJson$(SwaggerHttpService.scala:70)
	at mcc.movie.common.swagger.SwaggerDoc.generateSwaggerJson(SwaggerDoc.scala:17)
	at com.github.swagger.akka.SwaggerHttpService.$anonfun$routes$3(SwaggerHttpService.scala:107)
	at akka.http.scaladsl.server.directives.RouteDirectives.$anonfun$complete$1(RouteDirectives.scala:47)
	at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
	at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:61)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:43)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)

**Comment by nmarasoiu** [comment] 2017-12-04 12:46
we override schemes and, as the schemes type is immutable List, not sure if it is related or not (the exception seems to be an attempt to write into an immutable java List, but the causality may not be so direct). Thanks.

**Comment by pjfanning** [comment] 2017-12-04 12:55
Can you provide a test case?

**Comment by nmarasoiu** [comment] 2017-12-04 15:00
JRE: 1.8.0_141 (also JDK8 used when building).
Swagger is 1.5.16 (I guess a transitive dependency of swagger-akka-http but unsure)

**Comment by pjfanning** [comment] 2017-12-04 15:19
I have been unable to reproduce this issue

**Comment by nmarasoiu** [comment] 2017-12-05 08:10
I think it reproduces when the schemes are defined in both places, which are supposed to be reunited but in fact the first list below is immutable and crashes on addition:
- SwaggerGenerator.schemes (by default populated with HTTP)
- @SwaggerDefinition schemes
In my opinion it is bound to happen since the SwaggerGenerator.schemes is immutable.List and .asJava on it generates also an immutable SeqWrapper, and the reunion is done with Java style mutable add.
Thank you

**Comment by pjfanning** [comment] 2017-12-05 10:29
I've committed a change

**Closed by pjfanning** 2017-12-05 10:29 UTC
