### ISSUE TITLE
Required properties do not work for case class with fields of the same type

### ISSUE THREAD

**Issue by FVarya** [swagger-akka-http/swagger-akka-http#182] opened 2020-09-04 12:04 UTC
If case class contains more than one field of the same type, only the first field will be marked as required.
For `case class EchoList(val1: Int, val2: Int)` generated json will be
```
  "EchoList": {
    "required": [
      "val1"
    ],
    "type": "object",
    "properties": {
      "val1": {
        "type": "integer",
        "format": "int32"
      },
      "val2": {
        "type": "integer",
        "format": "int32"
      }
    }
  }
```
val2 missing in `required` array. 
Only explicit annotation for val2 will work:
`case class EchoList(val1: Int, @Schema(required = true) val2: Int)`
Is there any other way to make all non option fields required?

**Comment by pjfanning** [comment] 2020-09-04 22:39
Apologies but I don't spend much time on this code any more.

The issue is more to do with swagger-scala-module than swagger-akka-http. I tested it and reproduced the issue.
The issue does not appear to affect swagger v1, just swagger v2 - https://github.com/swagger-akka-http/swagger-scala-module/pull/59 appears to pass.

**Comment by pjfanning** [comment] 2020-09-06 11:22
closed in favour of https://github.com/swagger-akka-http/swagger-scala-module/issues/61

**Closed by pjfanning** 2020-09-06 11:22 UTC
