### ISSUE TITLE
Generated Swagger json removing route forward slash

### ISSUE THREAD

**Issue by hanrattyjen** [swagger-akka-http/swagger-akka-http#64] opened 2018-01-10 10:28 UTC
Some of the routes in the API I'm documenting end with a forward slash. 

When swagger-akka-http generates the documentation, this backslash is missing from the path.
Am I missing something? Unsure of why this is happening or how to fix it. Thanks!

```
    @Path("/User({user_id})/Report/")
    @ApiOperation(
      httpMethod = "GET",
      response = classOf[UserReport],
      responseContainer = "List",
      notes = "Example Request: /User(1)/Report/",
      value = "Get a list of reports for a user")
    @ApiImplicitParams(Array(
      new ApiImplicitParam(name = "user_id", value = "User ID", required = 
       true, example = "1", paramType = "path", dataType = "integer")
    ))
    @ApiResponses(Array(
      new ApiResponse(code = 200, message = "Successful response", 
       responseContainer = "Array", response = classOf[ReportList]),
      new ApiResponse(code = 404, message = "Requested resource not found", 
       response = classOf[ErrorDetails])
    ))
    def getReportList(@ApiParam(hidden = true) completeRouteMetadata: 
     CompleteRouteMetadata): Route = {
      (path("Report" /) & get) {
        pathEndOrSingleSlash {
          complete(ToResponseMarshallable(
           getReports(completeRouteMetadata.resourceOwner, List())))
        }
      }
    }
```

The generated json removes this:
```
/User({user_id})/Report:
    get:
      tags:
        - Report
      summary: Get a list of reports for the specified user
      description: 'Example Request: /User(1)/Report/'
      operationId: getReportList
      produces:
        - application/json
      parameters:
        - name: user_id
          in: path
          description: User ID
          required: true
          type: integer
          x-example: 1
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/ReportList'
        '404':
          description: Requested resource not found
          schema:
            $ref: '#/definitions/error'
```

**Comment by pjfanning** [comment] 2018-01-10 21:29
Duplicate of https://github.com/swagger-api/swagger-core/issues/2478

**Closed by pjfanning** 2018-01-10 21:29 UTC
